version: "2"

volumes:
  postgres-data:
    driver: local
  web-gems:
    driver: local
  redis_data:
    driver: local

services:
  redis:
    image: redis:3.2-alpine
    volumes: [ "redis_data:/data" ]
    ports: [ "6379:6379" ]
    command: redis-server --appendonly yes

  postgres:
    image: postgres:9.6.1-alpine
    ports:
      # We'll bind our host's port 5440 to postgres's port 5432, so we can use our database IDEs
      # with it:
      - 5432:5432
    volumes:
      - ./tmp:/tmp                             # Mount tmp folder
      - postgres-data:/var/lib/postgresql/data # Mount the postgres data volume
    environment: &postgres_env
      POSTGRES_PASSWORD: satlistanegra
      POSTGRES_USER:  postgres
      POSTGRES_DATABASE:  sat_lista_negra
      REDIS_URL: redis://redis:6379/web_development

  jobs: &web
    build:
      context: .
      dockerfile: Dockerfile
    image: vts-group/rails
    volumes:
      - .:/usr/src/app
      - web-gems:/usr/local/bundle

    links:
      - redis

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    command: sidekiq -c1
    environment:
      <<: *postgres_env
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_LOG_TO_STDOUT: "true"

  web:
    <<: *web
    command: rails server -p 3000 -b 0.0.0.0
    ports: [ "3000:3000" ]
    links:
      - postgres:db
